MyShop.WebUI/Controllers/BasketController.cs
using MyShop.Core.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyShop.WebUI.Controllers
{
    public class BasketController : Controller
    {
        IBasketService basketService;

        public BasketController(IBasketService service)
        {
            this.basketService = service;
        }

        // GET: Basket
        public ActionResult Index()
        {
            var model = basketService.GetBasketItems(this.HttpContext);
            return View(model);
        }

        //Add To Basket
        public ActionResult AddProduct(string Id)
        {
            basketService.AddToBasket(this.HttpContext, Id);
            return RedirectToAction("Index");
        }
        //Remove items from Basket
        public ActionResult RemoveProduct(string Id)
        {
            basketService.RemoveFromBasket(this.HttpContext, Id);
            return RedirectToAction("Index");
        }

        //partial view of the Basket 
        public PartialViewResult BasketSummary()
        {
            var basketSummary = basketService.GetBasketSummary(this.HttpContext);

            return PartialView(basketSummary);
        }


    }
}

MyShop.WebUI/Views/Basket/BasketSummary.cshtml
@model MyShop.Core.ViewModels.BasketSummaryViewModel


<ul class="nav navbar-nav navbar-right">

    <li>
        <a href="@Url.Action("Index", "Basket")">@Model.BasketCount items</a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Basket")">@String.Format("{0:c}", Model.BasketTotal)</a>
    </li>
</ul>

MyShop.WebUI/Views/Basket/Index.cshtml
@model IEnumerable<MyShop.Core.ViewModels.BasketItemViewModel>

@{ ViewBag.Title = "Basket"; }

<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            Line Total 
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img class="img-thumbnail" style="height:70px" src="~/Content/ProductImages/@item.Image" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @String.Format("{0:c}", item.Price)
            </td>
            <td>
                @String.Format("{0:c}", item.Price * item.Quantity)
            </td>

            <td>
                <a href="@Url.Action("RemoveProduct", "Basket", new { Id=item.Id})" class="btn btn-danger">Delete</a>
            </td>
        </tr>
    }
    <tr>
        <td colspan="4" style="text-align:right"><strong>Basket Total</strong></td>
        <td style="font-weight:bold; color:darkred;">@String.Format("{0:c}", (from p in Model select p.Price * p.Quantity).Sum())</td>
    </tr>

</table>